logging:
  level:
    root: info
    win.doyto.query.sql: debug
#    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: trace

doyto:
  query:
    config:
      table-format: "%s"
