logging:
  level:
    root: info
    win.doyto.query.sql: debug
#    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: trace

doyto:
  query:
    config:
      table-format: "%s"

spring:
  datasource:
    url: "jdbc:h2:mem:tpch;MODE=MySQL"
