
INSERT INTO REGION(SELECT * FROM CSVREAD('classpath:/data/region.tbl', 'R_REGIONKEY|R_NAME|R_COMMENT', 'charset=UTF-8 fieldSeparator=|'));
INSERT INTO NATION(SELECT * FROM CSVREAD('classpath:/data/nation.tbl', 'N_NATIONKEY|N_NAME|N_REGIONKEY|N_COMMENT', 'charset=UTF-8 fieldSeparator=|'));

INSERT INTO CUSTOMER(SELECT * FROM CSVREAD('classpath:/data/customer.tbl', 'C_CUSTKEY|C_NAME|C_ADDRESS|C_NATIONKEY|C_PHONE|C_ACCTBAL|C_MKTSEGMENT|C_COMMENT', 'charset=UTF-8 fieldSeparator=|')
    LIMIT 500
);

INSERT INTO PART(
SELECT * FROM CSVREAD('classpath:/data/part.tbl', 'P_PARTKEY|P_NAME|P_MFGR|P_BRAND|P_TYPE|P_SIZE|P_CONTAINER|P_RETAILPRICE|P_COMMENT', 'charset=UTF-8 fieldSeparator=|')
    LIMIT 1000
);

INSERT INTO SUPPLIER(
    SELECT * FROM CSVREAD('classpath:/data/supplier.tbl', 'S_SUPPKEY|S_NAME|S_ADDRESS|S_NATIONKEY|S_PHONE|S_ACCTBAL|S_COMMENT', 'charset=UTF-8 fieldSeparator=|')
    LIMIT 1000
);

INSERT INTO PARTSUPP(
    SELECT * FROM CSVREAD('classpath:/data/partsupp.tbl', 'PS_PARTKEY|PS_SUPPKEY|PS_AVAILQTY|PS_SUPPLYCOST|PS_COMMENT', 'charset=UTF-8 fieldSeparator=|')
    WHERE PS_PARTKEY IN (SELECT P_PARTKEY FROM PART)
      AND PS_SUPPKEY IN (SELECT S_SUPPKEY FROM SUPPLIER)
);

INSERT INTO ORDERS(
    SELECT * FROM CSVREAD('classpath:/data/orders.tbl', 'O_ORDERKEY|O_CUSTKEY|O_ORDERSTATUS|O_TOTALPRICE|O_ORDERDATE|O_ORDERPRIORITY|O_CLERK|O_SHIPPRIORITY|O_COMMENT', 'charset=UTF-8 fieldSeparator=|')
    WHERE O_CUSTKEY IN (SELECT C_CUSTKEY FROM CUSTOMER) LIMIT 10000
);

INSERT INTO LINEITEM(
    SELECT * FROM CSVREAD('classpath:/data/lineitem.tbl', 'L_ORDERKEY|L_PARTKEY|L_SUPPKEY|L_LINENUMBER|L_QUANTITY|L_EXTENDEDPRICE|L_DISCOUNT|L_TAX|L_RETURNFLAG|L_LINESTATUS|L_SHIPDATE|L_COMMITDATE|L_RECEIPTDATE|L_SHIPINSTRUCT|L_SHIPMODE|L_COMMENT', 'charset=UTF-8 fieldSeparator=|')
    WHERE L_PARTKEY IN (SELECT P_PARTKEY FROM PART)
      AND L_SUPPKEY IN (SELECT S_SUPPKEY FROM SUPPLIER)
      AND L_ORDERKEY IN (SELECT O_ORDERKEY FROM ORDERS)
    LIMIT 10000
);
